### ISSUE TITLE
Team-galbas

### ISSUE THREAD

**Issue by IjayAbby** [ahmetbozaci/tic-tac-toe#3]
Good job on the milestone, kindly fix the following and the project will work out fine.

- First of all, your linters don't pass all the test cases. Please fix this issue.

-  When I give an invalid input the game just switching its turn and not asking a repetitive input submission. You should add a logic that warns the user about invalid input. Please fix this issue.

-  The game should inform the player if the selected move is a draw move (without computing draw)

 - The game should inform the player if the selected move is a winning move (without computing the winning move)

**Comment by Lichapa** [comment]
Please fix the issues mentioned above.

**Comment by Rayan84** [comment]
All issues resolved
