### ISSUE TITLE
team-the-galbas

### ISSUE THREAD

**Issue by dibdas** [ahmetbozaci/tic-tac-toe#5]
-The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. (screenshot from Pathwright)

 -All game-logic related resources (classes and/or modules) are kept in the lib directory. (screenshot from Pathwright)
 concerning this attr_accessor :name, :mark its better to use either attr_readers/attr_writers. Only use attr_accessors if needed and be aware that by using it you are allow writing that property from outside the class. That variable can be set to anything

 -Lets validate input for numbers and white space.

**Comment by ahmetbozaci** [comment]
Fixed all  issues above that.
